TalentManagement.Web/Models/MyPassword/IndexModel.cs
using Resource = TalentManagement.Resources.Models.MyPassword.IndexModel;

namespace TalentManagement.Web.Models.MyPassword
{
    [LocalizedDisplayName("Title", typeof(Resource))]
    public class IndexModel
    {
        [LocalizedDisplayName("OldPassword", typeof(Resource))]
        public string OldPassword { get; set; }

        [LocalizedDisplayName("NewPassword", typeof(Resource))]
        public string NewPassword { get; set; }

        [LocalizedDisplayName("ConfirmPassword", typeof(Resource))]
        public string ConfirmPassword { get; set; }

        public string OldPasswordHashed { get; set; }
        public bool ValidationOk { get; set; }
    }
}

TalentManagement.Web/Models/MyPassword/Validation/IndexModelValidator.cs
using System.Web.Mvc;
using FluentValidation;
using TalentManagement.Infrastructure.Resources;
using TalentManagement.Infrastructure.Security;
using TalentManagement.Web.Models.Validation;

namespace TalentManagement.Web.Models.MyPassword.Validation
{
    internal class IndexModelValidator : AbstractValidator<IndexModel>,
                                             TalentManagement.Infrastructure.Validation.IValidator<IndexModel>
    {
        private readonly IResourceProvider _resourceProvider;
        private readonly IHashComputer _hashComputer;

        public IndexModelValidator() : 
            this(DependencyResolver.Current.GetService<IResourceProvider>(),
                 DependencyResolver.Current.GetService<IHashComputer>())
        {
        }

        public IndexModelValidator(IResourceProvider resourceProvider,IHashComputer hashComputer)
        {
            _resourceProvider = resourceProvider;
            _hashComputer = hashComputer;

            RuleFor(m => m.OldPassword)
                .NotEmpty();

            RuleFor(m => m.OldPassword)
                .Must((model, oldPassword) => oldPassword != null && _hashComputer.ComputeHash(oldPassword) == model.OldPasswordHashed)
               .WithMessage(_resourceProvider.ErrorPasswordInvalid);

            RuleFor(m => m.NewPassword)
                .NotEmpty();

            RuleFor(m => m.ConfirmPassword)
                .NotEmpty();
            
            RuleFor(m => m.ConfirmPassword)
                .Equal(m => m.NewPassword)
                .WithMessage(_resourceProvider.ErrorPasswordsMustMatch);


        }

        public TalentManagement.Infrastructure.Validation.ValidationResult ValidateInstance(IndexModel instance)
        {
            return this.ValidateAsModel(instance);
        }
    }
}

TalentManagement.Web/Controllers/MyPasswordController.cs
using System.Web.Mvc;
using TalentManagement.Domain.Users;
using TalentManagement.Infrastructure.Security;
using TalentManagement.Infrastructure.Validation;
using TalentManagement.Web.Models.MyPassword;
using TalentManagement.Web.Models.Validation;

namespace TalentManagement.Web.Controllers
{
    public class MyPasswordController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly IPrincipalProvider _principalProvider;
        private readonly IUserService _userService;

        public MyPasswordController(IUserRepository userRepository,
            IPrincipalProvider principalProvider,
            IUserService userService)
        {
            _userRepository = userRepository;
            _principalProvider = principalProvider;
            _userService = userService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(new IndexModel());
        }

        [HttpPost]
        public ActionResult Index(IndexModel indexModel)
        {
            //Due the security reasons do not want to pass password from model.
            indexModel.OldPasswordHashed = _userRepository.GetById(_principalProvider.GetUserName())
                                                       .HashedPassword;

            ValidationResult validationResult = ModelState.ValidateAndKeepState(indexModel);

            if (validationResult.IsValid)
            {
                _userService.ChangeUserPassword(_principalProvider.GetUserName(),indexModel.NewPassword);
            }

            indexModel.ValidationOk = validationResult.IsValid;
            return View(indexModel);
        }
    }
}

TalentManagement.Web/Views/MyPassword/Index.cshtml
@using Resource = TalentManagement.Resources.Models.MyPassword.IndexModel;
@using TalentManagement.Web.Models.MyPassword;
@model IndexModel

@{
    ViewBag.Title = @Html.LocalizedTextFor(m => m);
}

@section Head
{
    @Html.Bundles()
}

@using (Html.BeginForm("Index", "MyPassword", FormMethod.Post))
{
   <article class="row">
       <section class="span5">
           <div>
               @Html.ValidationSummary()
           </div>
           <div>
               @Html.LabelFor(m => m.OldPassword)
               @Html.PasswordStyledFor(m => m.OldPassword)
           </div>
           <div>
               @Html.LabelFor(m => m.NewPassword)
               @Html.PasswordStyledFor(m => m.NewPassword)
           </div>
           <div>
               @Html.LabelFor(m => m.ConfirmPassword)
               @Html.PasswordStyledFor(m => m.ConfirmPassword)
           </div>
       </section>
        <div class="span4 offset4">
            <button type="submit" class="btn btn-primary">@TalentManagement.Resources.UI.Update</button>
            @if (Model.ValidationOk)
            {
                <div id="updated" class="msgbar msg_Success hide_onC">
                    <span class="iconsweet">=</span><p>@Resource.PasswordUpdated</p>
                </div>
            }
        </div>
        
    </article>
}